services:
  - type: web
    name: irna-transporte
    env: python
    buildCommand: bash build.sh
    startCommand: cd webapp && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: KAGGLE_USERNAME
        sync: false
      - key: KAGGLE_KEY
        sync: false
